name = "ipxe-builder-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[vars]
FRONTEND_ORIGIN = "http://localhost:8080"
APP_BASE_URL = "http://127.0.0.1:8787"
GITHUB_APP_ID = "2856027"
GITHUB_APP_SLUG = "ipxe-builder-app-test"
TEMPLATE_OWNER = "allenyllee"
TEMPLATE_REPO = "ipxe-builder-template"
TEMPLATE_BRANCH = "main"
